'use babel';
export default {
    D2T_BREAK_DEL: 'D2T_BREAK_DEL',
    D2T_BREAK_ADD: 'D2T_BREAK_ADD',
    D2T_BREAK_DISABLE: 'D2T_BREAK_DISABLE',
    D2T_BREAK_ENABLE: 'D2T_BREAK_ENABLE',
    D2T_BREAK_INDEX: 'D2T_BREAK_INDEX',
    D2T_DEBUG_BGN: 'D2T_DEBUG_BGN',
    D2T_DEBUG_END: 'D2T_DEBUG_END',
    D2T_DEBUG_RESUME: 'D2T_DEBUG_RESUME',
    T2D_BREAK_ADD: 'T2D_BREAK_ADD',
    T2D_BREAK_DEL: 'T2D_BREAK_DEL',
    T2D_BREAK_SYNC: 'T2D_BREAK_SYNC'
};
